# Generated by Django 5.2 on 2025-05-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="template",
            field=models.CharField(
                choices=[
                    ("template1", "Şablon 1"),
                    ("template2", "Şablon 2"),
                    ("template3", "Şablon 3"),
                ],
                default="template1",
                max_length=20,
            ),
        ),
    ]
