# Generated by Django 5.2 on 2025-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvapp", "0002_cv_template"),
    ]

    operations = [
        migrations.RenameField(model_name="cv", old_name="name", new_name="ad",),
        migrations.RenameField(model_name="cv", old_name="phone", new_name="telefon",),
        migrations.RemoveField(model_name="cv", name="education",),
        migrations.RemoveField(model_name="cv", name="experience",),
        migrations.RemoveField(model_name="cv", name="skills",),
        migrations.RemoveField(model_name="cv", name="template",),
        migrations.AddField(
            model_name="cv", name="adres", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="cv_photos/"),
        ),
        migrations.AddField(
            model_name="cv",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="meslek",
            field=models.CharField(default="öğrenci", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv",
            name="soyad",
            field=models.CharField(default="hakay", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv", name="template_id", field=models.IntegerField(default=1),
        ),
    ]
