# Generated by Django 5.2 on 2025-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvapp", "0003_rename_name_cv_ad_rename_phone_cv_telefon_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="cv", old_name="ad", new_name="name",),
        migrations.RenameField(model_name="cv", old_name="telefon", new_name="phone",),
        migrations.RemoveField(model_name="cv", name="adres",),
        migrations.RemoveField(model_name="cv", name="foto",),
        migrations.RemoveField(model_name="cv", name="github",),
        migrations.RemoveField(model_name="cv", name="linkedin",),
        migrations.RemoveField(model_name="cv", name="meslek",),
        migrations.RemoveField(model_name="cv", name="soyad",),
        migrations.RemoveField(model_name="cv", name="template_id",),
        migrations.AddField(
            model_name="cv",
            name="education",
            field=models.TextField(default="balıkesir üniversitesi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv",
            name="experience",
            field=models.TextField(default="belediye"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv",
            name="skills",
            field=models.TextField(default="araştırma yapmak"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv",
            name="template",
            field=models.CharField(
                choices=[
                    ("template1", "Şablon 1"),
                    ("template2", "Şablon 2"),
                    ("template3", "Şablon 3"),
                ],
                default="template1",
                max_length=20,
            ),
        ),
    ]
