# Generated by Django 5.2 on 2025-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvapp", "0004_rename_ad_cv_name_rename_telefon_cv_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cv_photos/"),
        ),
        migrations.AlterField(
            model_name="cv", name="education", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cv", name="experience", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cv", name="name", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cv", name="skills", field=models.TextField(blank=True),
        ),
    ]
